name: Test

on:
- push
- pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm test

    - name: Dependabot Automerge
      if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
      uses: actions/github-script@v3
      with:
        script: |
          github.pulls.createReview({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.pull_request.number,
            event: "APPROVE"
          })
          github.pulls.merge({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.pull_request.number,
            merge_method: "squash"
          })
